main: net.simplyvanilla.nopluginscommand.NoPluginsCommand
name: NoPluginsCommand
description: Obfuscate commands for Anarchy servers.
version: @version@
api-version: 1.19

author: Simply Vanilla
website: https://github.com/SimplyVanilla/NoPluginsCommand

commands:
  customtext:
    description: Allow for admin defined messages
  suicide:
    description: Take the easy way out.
    usage: 'Usage: /<command>'
    aliases:
      - kill
